#
# @lc app=leetcode id=389 lang=python3
#
# [389] Find the Difference
#
# https://leetcode.com/problems/find-the-difference/description/
#
# algorithms
# Easy (57.78%)
# Likes:    1229
# Dislikes: 314
# Total Accepted:    257.6K
# Total Submissions: 445K
# Testcase Example:  '"abcd"\n"abcde"'
#
# You are given two strings s and t.
#
# String t is generated by random shuffling string s and then add one more
# letter at a random position.
#
# Return the letter that was added to t.
#
#
# Example 1:
#
#
# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.
#
#
# Example 2:
#
#
# Input: s = "", t = "y"
# Output: "y"
#
#
# Example 3:
#
#
# Input: s = "a", t = "aa"
# Output: "a"
#
#
# Example 4:
#
#
# Input: s = "ae", t = "aea"
# Output: "a"
#
#
#
# Constraints:
#
#
# 0 <= s.length <= 1000
# t.length == s.length + 1
# s and t consist of lower-case English letters.
#
#
#

# @lc code=start
from collections import Counter


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        t_count = Counter(t)
        s_count = Counter(s)

        for t_freq in t_count:
            if t_freq not in s_count or s_count[t_freq] != t_count[t_freq]:
                return t_freq

        return ""


# @lc code=end
